version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ( ./printtest.sh & echo $! >&3 ) 3>pid | ./test.sh
      - run: echo "made it out"

  
